Apply template standard
dltxio/react-template pull request #7
Opened 2022-04-12 07:02 UTC by rellfy

Fixes different issues and adds typechain with an example component.
Resolves #6

2022-04-12 07:36 UTC, bitcoinbrisbane commented on src/components/Welcome.tsx
> +          erc20Address={"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"}
May aswell use DLTx address :)

```suggestion
          erc20Address={"0xfa0B65413E3E81FAF7321f85b2AfdD0EffF13Ef5"}
```

2022-04-12 07:36 UTC, bitcoinbrisbane submitted a review, later dismissed
Lets change the address, and merge :)  Good job

2022-04-12 07:41 UTC, rellfy commented on src/components/Welcome.tsx
> +          erc20Address={"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"}
That address is the WETH address, not the input of balanceOf(). So I think the dltx address wouldn't work as it is not an ERC20? It checks the balance of the connected user. I added this component just to showcase typechain.

2022-04-12 08:21 UTC, drewflaherty commented on src/components/About.tsx
> -      <div></div>
This div needs to be here for the grid. Or at least an empty element <> </>

2022-04-12 08:21 UTC, drewflaherty commented on src/components/Erc20BalanceChecker.tsx
> +      if (signerAddress) setBalanceOf(await erc20.balanceOf(signerAddress));
Would be good to find a better example to demonstrate typechain because this component can be abstracted away using useBalance().
https://wagmi.sh/docs/hooks/useBalance

2022-04-12 08:21 UTC, drewflaherty commented on src/components/Welcome.tsx
> -      <div></div>
This div need to stay or be replace with and empty element.

2022-04-12 08:21 UTC, drewflaherty commented on src/hooks/useAccount.ts
>    return {
This file should probably be renamed to avoid confusion with the wagmi hook. Or deleted if not being used.

2022-04-12 08:33 UTC, bitcoinbrisbane commented on src/components/Welcome.tsx
> +          erc20Address={"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"}
Ok, ill let you make the call and resolve this.  Was just an idea :)

2022-04-12 22:42 UTC, xcjlo985 submitted a review, later dismissed
Can we please beef up the readme to contain a bit more context and explanation? Look at the nest template. This will help articulate the 'why' of things and it also helps more junior devs

2022-04-12 22:42 UTC, xcjlo985 commented on .eslintrc.js
> +    "@typescript-eslint/no-explicit-any": "off",
When does is make sense to use a eslint rule for a TS option vs just tsc?

2022-04-12 23:19 UTC, bazmatic commented on tsconfig.json
> +    "module": "ESNext",
Let's stick to lower case, as documented
```suggestion
    "module": "esnext",
```

2022-04-12 23:20 UTC, bazmatic commented on tsconfig.json
> +    "moduleResolution": "Node",
```suggestion
    "moduleResolution": "node",
```

2022-04-12 23:20 UTC, bazmatic commented on tsconfig.json
> +    "module": "ESNext",
TS documentation uses lower case
```suggestion
    "module": "esnext",
```

2022-04-12 23:22 UTC, bazmatic requested changes
Looks good, once the other reviewers' feedback has been incorporated.

2022-04-21 02:54 UTC, bazmatic commented
Closing this PR to deal with merges

2022-05-11 00:39 UTC, bazmatic approved these changes

2022-08-14 22:58 UTC, rellfy commented on src/components/Erc20BalanceChecker.tsx
> +      if (signerAddress) setBalanceOf(await erc20.balanceOf(signerAddress));
Will be made into a ticket after this PR is merged

2022-08-15 06:14 UTC, xiangzhe0812 approved these changes

2022-08-15 06:18 UTC, merged